### ISSUE TITLE
Input matrix header / rownames

### ISSUE THREAD

**Issue by blmoore** [blajoie/crane-nature-2015#1]
Supplying a raw matrix of numbers throws `ERROR: Must supply headered matrix!`

Does this mean inputs must have headers in the format of your example inputs (something like `bin#|genome|chr:bp-bp`)? Would be helpful to document either way (apologies my perl is too rusty to figure this out from the source).

**Comment by blajoie** [comment]
Yes the matrix must have headers.
(will add additional documentation - sorry!)

Header format is:
name|assembly|chr:start-end

e.g.
bin1|hg19|chr1:200000-240000
(header name must be unique)

This script only works on symmetrical, binned data (fixed size bin).

**Comment by blmoore** [comment]
Great, thanks!
