### ISSUE TITLE
how to create the input matrix?

### ISSUE THREAD

**Issue by francisfa** [blajoie/crane-nature-2015#7]
sorry, i convert the HiC-Pro output matrix to dense matrix, and I add the row name and col name to this matrix. there is always a error:
Illegal division by zero at scripts/matrix2insulation.pl line 561.
i do not know what is the $headerSpacing? so, how to create the input file?
thanks!

**Comment by lixiaoms** [comment]
I had a similar question with you and solved by using the format of rownames/colnames of matrix in test/input
it likes:
/tbinxxx|xxx|chrxxx:xxx-xxx/tbinxxx|xxx|chrxxx:xxx/t....

**Comment by francisfa** [comment]
Many thanks!
